export const cards = [
    {
        id: "1",
        header: "Безлимитный 300",
        sum: "300",
        text: "до 10 Мбит/сек",
        blueВackgroundHeader: true,
        colorBlueCard: true,
    },
    {
        id: "2",
        header: "Безлимитный 450",
        sum: "450",
        text: "до 50 Мбит/сек",
        greenВackgroundHeader: true,
        colorGreenCard: true,
    },
    {
        id: "3",
        header: "Безлимитный 550",
        sum: "550",
        text: "до 100 Мбит/сек",
        isSelected: true,
        redВackgroundHeader: true,
        colorRedCard: true,
    },
    {
        id: "4",
        header: "Безлимитный 1000",
        sum: "1000",
        text: "до 200 Мбит/сек",
        blackВackgroundHeader: true,
        colorBlackCard: true,
    },
];
